README.md
gradle.properties
gradle/vertx.gradle
src/main/java/li/chee/vertx/redisques/RedisQues.java
src/main/java/li/chee/vertx/redisques/handler/AddItemHandler.java
src/main/java/li/chee/vertx/redisques/handler/DeleteAllQueueItems.java
src/main/java/li/chee/vertx/redisques/handler/DeleteLockHandler.java
src/main/java/li/chee/vertx/redisques/handler/GetAllLocksHandler.java
src/main/java/li/chee/vertx/redisques/handler/GetItemHandler.java
src/main/java/li/chee/vertx/redisques/handler/GetListRangeHandler.java
src/main/java/li/chee/vertx/redisques/handler/GetLockHandler.java
src/main/java/li/chee/vertx/redisques/handler/PutLockHandler.java
src/main/java/li/chee/vertx/redisques/handler/ReplaceItemHandler.java
src/test/java/li/chee/vertx/redisques/AbstractTestCase.java
src/test/java/li/chee/vertx/redisques/RedisQuesTest.java

Updated vertx-redisques module to Vert.x v3.2.0
Please review and eventually merge ;-)
Drone.io successfully builded. See https://drone.io/github.com/mcweba/vertx-redisques/4

Update to Vert.x v3.2.0

---

README.md
gradle.properties
src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java

Please merge.
Successfull tests: https://drone.io/github.com/mcweba/vertx-redisques/37

Added RedisquesConfiguration class for simplyfied configuration of the module

---

gradle.properties
src/main/java/org/swisspush/redisques/RedisQues.java
src/test/java/org/swisspush/redisques/AbstractTestCase.java

Some minor changes.
Tests successfully:
- https://drone.io/github.com/mcweba/vertx-redisques/39
- https://drone.io/github.com/mcweba/vertx-redisques/40

Using RedisquesConfiguration in unit tests

---

gradle.properties
src/main/java/org/swisspush/redisques/RedisQues.java

please review and merge.
Successful tests: https://drone.io/github.com/mcweba/vertx-redisques/1

Fix RedisQues.resetConsumers() method. This fixes #11

---

README.md
build.gradle
gradle.properties
src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/RedisQuesRunner.java
src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
src/main/java/org/swisspush/redisques/util/StatusCode.java
src/test/java/org/swisspush/redisques/AbstractTestCase.java
src/test/java/org/swisspush/redisques/RedisQuesProcessorTest.java
src/test/java/org/swisspush/redisques/RedisQuesTest.java
src/test/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandlerTest.java
src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java

Please review and eventually merge the implementation of the HTTP API for Redisques.
Tests run sucessfully: https://drone.io/github.com/swisspush/vertx-redisques/73
Cheers

Redisques http request handler

---

pom.xml

this should fix the wrong versions

merging develop branch

---

src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java

This prepares code for following error handling. Doesn't fix issue yet.
- Remove multiple getter calls

[#59] Simple refactoring

---

src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
src/main/java/org/swisspush/redisques/lua/LuaScriptManager.java
src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java
src/main/java/org/swisspush/redisques/util/MessageUtil.java
src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
src/test/java/org/swisspush/redisques/RedisQuesTest.java
src/test/java/org/swisspush/redisques/util/MessageUtilTest.java
src/test/java/org/swisspush/redisques/util/RedisquesAPITest.java

- Some smaller refactoring.
- Eliminate some duplicates.
- Drop some (hopefully useless) null checks.
- Improve some logs by also print stack.
- Don't use Optional as method arguments.

[#60] Fix less relevant findings

---

pom.xml
src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
src/main/java/org/swisspush/redisques/lua/LuaScriptManager.java
src/main/java/org/swisspush/redisques/lua/LuaScriptState.java
src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java
src/main/java/org/swisspush/redisques/util/MessageUtil.java
src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
src/test/java/org/swisspush/redisques/RedisQuesTest.java
src/test/java/org/swisspush/redisques/util/MessageUtilTest.java
src/test/java/org/swisspush/redisques/util/RedisquesAPITest.java

PR for new release containing the issues:
* [#59 Stabilize RedisQues by improving error handling (review of v2.5.1)](https://github.com/swisspush/vertx-redisques/issues/59)
* [#60 Less relevant findings from code (review of v2.5.1)](https://github.com/swisspush/vertx-redisques/issues/60)

PR for new release

---

src/main/java/org/swisspush/redisques/util/RedisquesAPI.java

Minor change to make it look as specified.

SDCISA-3814 Correction of TimeUnit attribute name

---

src/main/java/org/swisspush/redisques/util/DefaultRedisProvider.java
src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
src/test/java/org/swisspush/redisques/util/DefaultRedisquesConfigurationProviderTest.java

- added username and password authentication
Made redisques aware of new ACL authentication method introduced with Redis 6.

[SDCISA-13110] Support Redis 6.x authentication method

---

src/main/java/org/swisspush/redisques/util/DefaultRedisProvider.java
src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java

- made redis client aware of redis cluster

[SDCISA-13222] K8S: vertx-redisques

---

src/test/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandlerTest.java

With this PR we now verify the result in a dynamic manner (and not after some fixed time).

Stabilize the RedisquesHttpRequestHandlerTest

---

src/main/java/org/swisspush/redisques/RedisQues.java

One (of many) examples cited from log:
```
2024-04-03T12:18:18,368 test houston WARN BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-5,5,main] has been blocked for 135 ms, time limit is 8 ms
io.vertx.core.VertxException: Thread blocked
at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:?]
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:?]
at sun.nio.ch.IOUtil.write(IOUtil.java:50) ~[?:?]
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462) ~[?:?]
at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:415) ~[netty-transport-4.1.103.Final.jar:4.1.103.Final]
at …
```

[SDCISA-13746] Reduce EvLoop blocking time while publishing QueueStats

---

src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java

With this PR we do two things
a) move execution of tasks to worker thread in order to offload the event loop threads
b) execute redis operations sequentially in stead of in parallel

QueueStatisticCollector blocks event loop threads fixed

---

src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java

I don't exactly understand what the original code did. But I tried to keep behavior as far I was able to understand it.

Try replace some (probably sequential, aka too slow) code

---

src/main/java/org/swisspush/redisques/performance/UpperBoundParallel.java

Code-format as requested in earlier PR

---

src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/performance/UpperBoundParallel.java
src/test/java/org/swisspush/redisques/performance/UpperBoundParallelTest.java

In recent PR #194 to fix resource exhaustion, I accidentally introduced another leak where the limit tokens don't get released.

Fix recently introduced resource leak and add some tests to cover it

---

src/main/java/org/swisspush/redisques/QueueStatsService.java

Not sure why this code suddenly is no longer used. But as it is, likely makes sense to get rid of it.

Cleanup some dead code

---

src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/lock/Lock.java
src/main/java/org/swisspush/redisques/lock/impl/RedisBasedLock.java
src/main/java/org/swisspush/redisques/lock/lua/LockLuaScripts.java
src/main/java/org/swisspush/redisques/lock/lua/ReleaseLockRedisCommand.java
src/main/java/org/swisspush/redisques/lua/LuaScript.java
src/main/java/org/swisspush/redisques/lua/LuaScriptState.java
src/main/java/org/swisspush/redisques/lua/RedisCommand.java
src/main/java/org/swisspush/redisques/lua/RedisCommandDoNothing.java
src/main/java/org/swisspush/redisques/util/FailedAsyncResult.java
src/main/java/org/swisspush/redisques/util/LockUtil.java
src/main/resources/lock_release.lua
src/test/java/org/swisspush/redisques/lock/impl/RedisBasedLockTest.java
src/test/java/org/swisspush/redisques/util/LockUtilTest.java

Added no reviewers since the implementation is a 1:1 copy of the feature in gateleen.

#228 Add lock mechanism to prevent multiple task executions

---

src/main/java/org/swisspush/redisques/scheduling/PeriodicSkipScheduler.java

Enhance documentation by an example to reduce future issues similar to https://github.com/swisspost/vertx-redisques/pull/254 .

Enhance doc based on what we had to fix.

---

src/main/java/org/swisspush/redisques/QueueStatsService.java
src/main/java/org/swisspush/redisques/RedisQues.java
src/main/java/org/swisspush/redisques/RedisQuesBuilder.java
src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
src/main/java/org/swisspush/redisques/queue/QueueActionsService.java
src/main/java/org/swisspush/redisques/queue/QueueProcessingState.java
src/main/java/org/swisspush/redisques/queue/UnregisterConsumerType.java

moved inner classes out, and moved dequeue statistic related into QueueStatsService

Refactor redis ques verticle break down 1

---

src/main/java/org/swisspush/redisques/util/DefaultMemoryUsageProvider.java
src/test/java/org/swisspush/redisques/util/DefaultMemoryUsageProviderTest.java

#178 - SDCISA-21338 fix memory evaluation
