swisspost/vertx-redisques

- src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
- src/test/java/org/swisspush/redisques/RedisQuesTest.java
- src/test/java/org/swisspush/redisques/util/RedisquesAPITest.java
Ensured API backward compatibility by allowing the "old" queue operation names to work too.
Tests: https://drone.io/github.com/mcweba/vertx-redisques/48
Please review and merge
> Ensure API backward compatibility

- src/main/java/org/swisspush/redisques/RedisQues.java
This avoids waiting for the next cleanup and reschedule faster the queue consumption faster. Advantages:
- Faster retry.
- Less queue growth in case of short failures.
- Cleanup then concerns only orphaned queues after node shutdown/reboot, less load on checkQueues in case of many blocked queues.
> Schedule consumer notification after processing failure

- README.md
- gradle.properties
- gradle/vertx.gradle
- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/lua/LuaScript.java
- src/main/java/org/swisspush/redisques/lua/LuaScriptManager.java
- src/main/java/org/swisspush/redisques/lua/LuaScriptState.java
- src/main/java/org/swisspush/redisques/lua/RedisCommand.java
- src/main/java/org/swisspush/redisques/lua/RedisCommandDoNothing.java
- src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/main/resources/redisques_cleanup.lua
- src/test/java/org/swisspush/redisques/AbstractTestCase.java
- src/test/java/org/swisspush/redisques/lua/AbstractLuaScriptTest.java
- src/test/java/org/swisspush/redisques/lua/RedisCleanupLuaScriptTests.java
- src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java
Please review and eventually merge
Tests: https://drone.io/github.com/mcweba/vertx-redisques/4
**Why lua?**
Redis provides additonal options for the **set** command. These options are available in _io.vertx.redis.RedisClient_ but the handler for the return value is a **Handler\<AsyncResult\<Void\>\>**. So the needed information cannot be accessed. This problem will be fixed with vert.x version 3.3.0. 
I made another issue to replace the lua implementation with the RedisClient method. See #15
> Pull Request for issue #10

- build.gradle
- src/main/java/org/swisspush/redisques/RedisQues.java
- src/test/java/org/swisspush/redisques/AbstractTestCase.java
- src/test/java/org/swisspush/redisques/RedisQuesProcessorTest.java
- src/test/java/org/swisspush/redisques/RedisQuesTest.java
Please review and eventually merge.
Tests have been successfully executed: See [https://drone.io/github.com/swisspush/vertx-redisques/56](https://drone.io/github.com/swisspush/vertx-redisques/56)
Additional tests are:
- RedisQuesProcessorTest.queueProcessorShouldBeNotifiedWithNonLockedQueue
- RedisQuesProcessorTest.queueProcessorShouldNotBeNotNotifiedWithLockedQueue
> Do not notify consumers with locked queues #18

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
Redis server can be configured to require a password for client connections.
See [AUTH command](https://redis.io/commands/auth) and [redis.conf - 'requirepass'](https://redis.io/topics/security)
This PR enables vertx-redisques to be able to connect to such protected Redis server. The correct AUTH password has to be provided to the vertx-redisques module.
> Use an optional AUTH (password) to access Redis server

- gradle.properties
Due to https://github.com/vert-x3/vertx-redis-client/issues/65 we need an up-to-date RedisClient for RedisQues (i.e. 3.4.2 which includes the fix)
Recompilation is required due to a small change in a method signature: a parameter type of`RedisClient.expire(...)` changed from `int` to `long`.
Unfortunately it's not possible to have one RedisQues which works with redis-client 3.3.3 **and** 3.4.2
A complete update of Gateleen to 3.4.2 is not possible with limited effort - but we need a quick fix.
So we decided to mix JARs: Vertx basically in version 3.3.3, only redis-client updated to 3.4.2
> Compile against redis-client 3.4.2

- src/main/java/org/swisspush/redisques/RedisQues.java
Use Logger#error(Object,Throwable) instead, to also log the real cause
of our error.
> Log exception too in case enqueuing fails

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/lua/LuaScriptState.java
- Add error handling for asynchronous operations.
- Add missing 'break' in switch statement.
- Dropped useless null checks.
- Eliminated some repeated getter calls.
> [#59] Stabilize RedisQues by improving error handling

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/test/java/org/swisspush/redisques/RedisQuesProcessorTest.java
- get rid of this RedisQues internal 'delivery timeout' timer
- use Vertx' DeliveryOption when sending the message to the Consumer (QueueProcessor) and set the processorTimeout value (240 seconds) 
This simplifies the code and effectively enables delivery timeouts > 30 seconds
Solves #66
> Use DeliveryOption instead of a timer to detect timeouts on the EventBus

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/util/QueueConfiguration.java
- src/test/java/org/swisspush/redisques/RedisQuesTest.java
- src/test/java/org/swisspush/redisques/slowdown/EnqueueThrottleTest.java
- src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java
Background: Redis-Memory is limited - therefore queue sizes are limited (queue length multiplied with average queue entry size).
So at some point, EN-queuing suddenly fails (presumed that DE-queuing is not possible for a while)
For stability reasons we now can slowly increase a backpressure towards EN-queuing process (http- or EventBus-Clients) by delaying a "success enqueue"-reply more and more. Presuming that the originating EN-queuing process also works sequentially (i.e. it only requests to enqueue a next message when the previous message is successfully enqueued) this simple mechano helps to secure 'our' Redis memory and give us more time (minutes or even hours) to react.
There are now two additonal config options 'per QueueName-pattern':
- enqueueDelayMillisPerSize
- …
> New feature "Enqueue-Slowdown" (or -Throttling)

- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/test/java/org/swisspush/redisques/handler/DisableQueueNameEncodingTest.java
An earlier change introduced a bug when queue names contained plus signs, when decoding, these would be converted to spaces.
This doesn't directly address this bug, but instead it allows the disabling of the decoding mechanism.
> Allow disable of queuename decoding

- src/main/java/org/swisspush/redisques/RedisQues.java
Discovered this when working on the gateleen integration tests. We need to handle the null case here.
> handle null result

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/handler/GetAllLocksHandler.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesHandler.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesItemsCountHandler.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesStatisticsHandler.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/lua/LuaScript.java
- src/main/java/org/swisspush/redisques/lua/LuaScriptManager.java
- src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java
- src/main/java/org/swisspush/redisques/util/QueueHandlerUtil.java
- src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java
- src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/main/resources/redisques_mllen.lua
- src/test/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandlerTest.java
- src/test/java/org/swisspush/redisques/slowdown/EnqueueThrottleTest.java
- src/test/java/org/swisspush/redisques/util/RedisquesAPITest.java
Currently there was only a monitor request which was requesting in a sequence the size of each queue over the vert.x eventbus.  With a high number of queues this is inefficient.  In addition, there is the need for an efficient way to retrieve more queue statistic values about slowdown time and backpressure time. This PR introduces a LUA script fetching all queue sizes in one go and provides as well all statistic values of the queues in one single request.
> #84 - SDCISA-3814 Provide efficient statistics API for Queue monitoring

- README.md
- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesPaceHandler.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesSpeedHandler.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java
- src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/test/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandlerTest.java
- src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java
Additional feature allowing to evaluate the message pace for a certain queue or group of queues defined by a regex filter. This allows to easily evaluate the pace as well for queues which are dynamically labelled by given header discrimators.
> #84 / SDCISA-3814 Queue pace (speed) evaluation feature added

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/test/resources/log4j.xml
We see a lot of these warnings in our project
} else {
// Somehow registration changed. Let's renotify.
log.warn("Registration for queue " + queueName + " has chhas changed to " + consumer);
The goal of this PR is to get rid of them. We now wait for async methods to complete prior to continue execution where not the case yet.
> await completion of async methods (WARN Registration for queue " + queueName + " has chhas changed to " + consumer)

- src/main/java/org/swisspush/redisques/util/HttpServerRequestUtil.java
- src/test/java/org/swisspush/redisques/util/HttpServerRequestUtilTest.java
This is related to https://github.com/eclipse-vertx/vert.x/pull/3123
With this PR we support two payloads encoding formats:
- the new format (base64url)
- the old format (plain base64)
This should allow us to migrate to the "new format"
> use apache base64 decoder

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesStatisticsHandler.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/util/DequeueStatistic.java
- src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java
- src/main/java/org/swisspush/redisques/util/RedisquesAPI.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/test/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandlerTest.java
- src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java
With this PR we are able to monitor details regarding the dequeueing, namely
lastDequeueAttemptTimestamp
lastDequeueSuccessTimestamp
nextDequeueDueTimestamp
This allows us to easily identify e.g. 
- an  overload situation where queues are not longer processed (dequeue is no longer attempted)
- dequeue was attempted but failed
> Added dequeue statistics

- src/main/java/org/swisspush/redisques/RedisQues.java
As per title, small but meaningful fix, we need to check the outcome when setting the timestamp when we last successfully delivered a queue item to the destination.
> fixed retry timestamp

- pom.xml
Libraries must not include logger implementations. It is the applications choice which logger implementation to use. Not a libraries one. Including logger implementations from within libraries defeats the whole purpose of having a logging facade at all. As apps need to configure all logger impls pulled in somewhere by some library deep down the dependency tree.
Example:
```
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [org.slf4j.reload4j.Reload4jServiceProvider@3b084709]
SLF4J: Found provider [org.apache.logging.slf4j.SLF4JServiceProvider@3224f60b]
```
> [SDCISA-15223] Drop logger implementation dependency

- src/main/java/org/swisspush/redisques/RedisQues.java
Occurs ways too often. And as nobody complains for years, it seems NOT to be a warning really.
> Tune log level

- src/main/java/org/swisspush/redisques/QueueStatsService.java
- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/util/DequeueStatistic.java
- src/main/java/org/swisspush/redisques/util/DequeueStatisticCollector.java
- src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java
With this PR we fix an issue where we got inconsistent stats due to the distribution of queue processing to multiple verticles. The stats are no shared across the verticles using https://vertx.io/docs/vertx-core/java/#_using_the_shareddata_api
> Dequeue monitor timestamps incorrect fixed

- src/main/java/org/swisspush/redisques/QueueStatsService.java
- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/action/GetQueueItemsCountAction.java
- src/main/java/org/swisspush/redisques/action/GetQueuesItemsCountAction.java
- src/main/java/org/swisspush/redisques/exception/ExceptionFactory.java
- src/main/java/org/swisspush/redisques/exception/NoStackReplyException.java
- src/main/java/org/swisspush/redisques/exception/NoStacktraceException.java
- src/main/java/org/swisspush/redisques/exception/ThriftyExceptionFactory.java
- src/main/java/org/swisspush/redisques/exception/WastefulExceptionFactory.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesItemsCountHandler.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/scheduling/PeriodicSkipScheduler.java
- src/main/java/org/swisspush/redisques/util/QueueActionFactory.java
- src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java
- src/main/java/org/swisspush/redisques/util/StatusCode.java
Relates to SDCISA-15833, Probably fixes https://github.com/swisspost/vertx-redisques/pull/170 .
Usage example (*replace dots with your respective quota*):
```java
RedisQues.builder()
.withRedisMonitoringReqQuota(...)
.withCheckQueueRequestsQuota(...)
.withQueueStatsRequestQuota(...)
.withGetQueuesItemsCountRedisRequestQuota(...)
.build();
```
If nothing is configured, RedisQues will use INT_MAX to emulate the behavior as it was before.
> Apply backpressure in misc places to prevent resource exhaustion issues

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesItemsCountHandler.java
- src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
- src/main/java/org/swisspush/redisques/util/DefaultRedisProvider.java
- src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java
- src/main/java/org/swisspush/redisques/util/RedisProvider.java
With this PR we remove below method and always use the RedisAPI
RedisProvider
Future<Redis> connection();
> Always use the RedisAPI

- src/main/java/org/swisspush/redisques/QueueStatsService.java
- src/main/java/org/swisspush/redisques/action/AbstractQueueAction.java
- src/main/java/org/swisspush/redisques/action/GetQueueItemsAction.java
- src/main/java/org/swisspush/redisques/exception/RedisQuesExceptionFactory.java
- src/main/java/org/swisspush/redisques/exception/ThriftyRedisQuesExceptionFactory.java
- src/main/java/org/swisspush/redisques/exception/WastefulRedisQuesExceptionFactory.java
- src/main/java/org/swisspush/redisques/handler/AddQueueItemHandler.java
- src/main/java/org/swisspush/redisques/handler/DeleteLockHandler.java
- src/main/java/org/swisspush/redisques/handler/GetLockHandler.java
- src/main/java/org/swisspush/redisques/handler/GetQueueItemHandler.java
- src/main/java/org/swisspush/redisques/handler/GetQueuesItemsCountHandler.java
- src/main/java/org/swisspush/redisques/handler/PutLockHandler.java
- src/main/java/org/swisspush/redisques/handler/ReplaceQueueItemHandler.java
- src/test/java/org/swisspush/redisques/action/AbstractQueueActionTest.java
- src/test/java/org/swisspush/redisques/action/AddQueueItemActionTest.java
- src/test/java/org/swisspush/redisques/action/BulkDeleteQueuesActionTest.java
- src/test/java/org/swisspush/redisques/action/DeleteAllQueueItemsActionTest.java
- src/test/java/org/swisspush/redisques/action/DeleteLockActionTest.java
- src/test/java/org/swisspush/redisques/action/DeleteQueueItemActionTest.java
- src/test/java/org/swisspush/redisques/action/GetAllLocksActionTest.java
- src/test/java/org/swisspush/redisques/action/GetLockActionTest.java
- src/test/java/org/swisspush/redisques/action/GetQueueItemActionTest.java
- src/test/java/org/swisspush/redisques/action/GetQueueItemsActionTest.java
- src/test/java/org/swisspush/redisques/action/PutLockActionTest.java
- src/test/java/org/swisspush/redisques/action/ReplaceQueueItemActionTest.java
Related:
- [Example how stripped error messages make finding bugs unecessary hard](https://github.com/swisspost/gateleen/issues/589)
- [ReplyException](https://github.com/eclipse-vertx/vert.x/blob/4.5.1/src/main/java/io/vertx/core/eventbus/ReplyException.java#L16-L24)
- [ReplyFailure](https://github.com/eclipse-vertx/vert.x/blob/4.5.1/src/main/java/io/vertx/core/eventbus/ReplyFailure.java#L34-L37)
- [reply(Throwable) allows more detailed error messages than fail(int, String) does](https://github.com/eclipse-vertx/vert.x/blob/4.5.1/src/main/java/io/vertx/core/eventbus/impl/CodecManager.java#L101-L105)
> Pass error information through to caller in place of out-of-context logging

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java
With this PR we
a) use the so called PeriodicSkipScheduler to avoid parallel execution of periodic tasks (in this case queue processing)
b) we make the consumer lock multiplier configurable, the current value used becomes the default
c) log more timing related information
> Ensure that checkQueues() is not executed in parallel, more logs added

- src/main/java/org/swisspush/redisques/RedisQues.java
With this PR we periodically (every 20s) log how many queues each verticle instance is currently processing. This is done only if the log level is at least DEBUG. "Currently processing" means that the verticle has placed a so called "consumer lock" onto the queue.
Additionally some output is now logged on TRACE level to avoid overload when set to DEBUG.
> Log number of queues locked on a per RedisQues Verticle instance base

- src/main/java/org/swisspush/redisques/RedisQues.java
Cited from UpperBoundParallel.Mentor:
```java
/**
* Called once as soon the iteration has ended SUCCESSFULLY. It is NOT
* called if {@link #onError(Throwable, Object)} did request to STOP the
* iteration for example.
*/
void onDone(Ctx ctx);
```
Related:
- SDCISA-18274
> SDCISA-18049: Fix dead queues

- src/main/java/org/swisspush/redisques/performance/UpperBoundParallel.java
Helps to hunt mis-behaving UpperBoundParallel usages. To find the caller, debug log level can be enabled which prints a stack where the mis-behaving caller (*hopefully*) is listed in.
> SDCISA-18302: Add logging in case unreachable code gets reached.

- src/main/java/org/swisspush/redisques/RedisQues.java
With this PR we fix an issue where registrations pointing to no longer existing consumers continue to be refreshed after a server restart
> Cleanup consumers that are no longer alive

- src/main/java/org/swisspush/redisques/RedisQues.java
- src/main/java/org/swisspush/redisques/util/RedisquesConfiguration.java
- src/test/java/org/swisspush/redisques/util/RedisquesConfigurationTest.java
With this PR the RedisQues instances unregister queues that are "quiet" (empty and idle) in order to release resources.
> Cleanup queues that are empty & idle 

- src/main/java/org/swisspush/redisques/RedisQues.java
java.lang.NullPointerException: Cannot read field "state" because the return value of "java.util.Map.get(Object)" is null
at org.swisspush.redisques.RedisQues.lambda$consume$36(RedisQues.java:1007) ~[redisques-4.1.13.jar:?]
at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176) ~[vertx-core-4.5.1.jar:4.5.1]
at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66) ~[vertx-core-4.5.1.jar:4.5.1]
> fix unhandled exception

- src/main/java/org/swisspush/redisques/queue/QueueRegistryService.java
io.vertx.core.VertxException: Thread blocked
at java.base/java.security.MessageDigest.isEqual(Unknown Source)
at java.base/com.sun.crypto.provider.GaloisCounterMode.init(Unknown Source)
at java.base/com.sun.crypto.provider.GaloisCounterMode.engineInit(Unknown Source)
at java.base/javax.crypto.Cipher.init(Unknown Source)
at java.base/sun.security.ssl.SSLCipher$T13GcmWriteCipherGenerator$GcmWriteCipher.encrypt(Unknown Source)
at java.base/sun.security.ssl.OutputRecord.t13Encrypt(Unknown Source)
at java.base/sun.security.ssl.OutputRecord.encrypt(Unknown Source)
at java.base/sun.security.ssl.SSLEngineOutputRecord.encode(Unknown Source)
at java.base/sun.security.ssl.SSLEngineOutputRecord.encode(Unknown Source)
at java.base/sun.security.ssl.SSLEngineImpl.encode(Unknown Source)
at …
> the slow ssl may casue thread blocked exception
